### ISSUE TITLE
Hidden categories should not be displayed in the data feed

### ISSUE THREAD

**Issue by carlosescri** [doofinder/doofinder-magento#1]
Currently we ignore the visibility of the category.

- If a category is hidden, don't display it.
- If a category is visible but is a descendant of a hidden category, don't display it.

**Comment by stefanschwann** [comment]
Do you know when this issue will be solved?
We are using Magento 1.5.0.1 and all hidden categories are also shown. This should not happen.

**Comment by carlosescri** [comment]
@stefanschwann I don't really know. We are in conversations with a group of Magento experts that will help us dealing with this kind of issues but I can't give you an exact date.
