### ISSUE TITLE
When you replace the magento search, you only get the first 100 results every time.

### ISSUE THREAD

**Issue by zarapico** [doofinder/doofinder-magento#100]
When you replace the magento search, you only get the first 100 results every time.

It has been tested on 3 magento installations with magento versions 1.9.3.1, 1.9.3.3 and 1.9.3.4
The issue is apparently found in the prepareResult method https://github.com/doofinder/doofinder-magento/blob/master/app/code/community/Doofinder/Feed/Model/CatalogSearch/Resource/Fulltext.php#L74

**Comment by carlosescri** [comment]
@zarapico the search works this way:

- We get the first 100 products and compare with first results in the Magento's search cache.
- If nothing changed we let Magento continue with the search based on the search results cache.
- If changed, we get all results (until the limit specified in the module, 500 items if I'm not wrong) from Doofinder and update Magento's search cache.

To check if this works you can perform a search so results are cached. Then, update boosting for a product from the Doofinder panel so it changes the order of results, and search again. If it changes and appears in the same order as in boosting, it's working.

This assumes that Doofinder works properly and, if you don't find what you're searching for in the first 100 items then it's not there.

If you think this behavior is not actually working, please give more details and examples.

Thanks!

**Comment by zarapico** [comment]
Hi @carlosescri ,
Thanks for your quick response!
Then it is not possible to show more than 100 results, right?

For example, if we have a very large catalog in Instant Search (JS)
![image](https://user-images.githubusercontent.com/6150209/28258605-4b2d2622-6ad2-11e7-92b6-02ac05a0e3da.png)

While with the magento search we get only 100
![image](https://user-images.githubusercontent.com/6150209/28258635-7838c8ba-6ad2-11e7-8489-41354cce9580.png)

Is this correct for the logic of your module?
Thanks!

PS: the tests have been done on (https://www.normacomics.com/) for if you prefer to have a look

**Comment by carlosescri** [comment]
Hi @zarapico,

Actually not. In this case we need some help to fix the problem. Could you send an e-mail to support@doofinder.com with a reference to this issue? We can continue the discussion from there.

Thanks!

**Comment by carlosescri** [comment]
(I see that the site's in Spanish, you can use that language if you want :wink:)

**Comment by carlosescri** [comment]
This should be fixed in #102
