### ISSUE TITLE
Cron error message in Admin

### ISSUE THREAD

**Issue by dblakemore** [doofinder/doofinder-magento#103]
Product Data Feed > Feed Status: Always shows a message saying **There are no registered cron tasks. Please, check your system's crontab configuration**. Seem to be an issue with the way in which the **$lastSchedule** record is accessed. I have patched this locally on my site, so I will submit a fix for it that you can review

**Comment by carlosescri** [comment]
Hi @dblakemore, this should be fixed [in the latest release](https://github.com/doofinder/doofinder-magento/releases/tag/v1.8.15). Have you tried updating the module via Magento Connect prior to sending a patch? 🤔

**Comment by dblakemore** [comment]
Hi Carlos,

Yes I've just reviewed it and can confirm the it is actually fixed. Apologies. I was was reviewing the recent commits and missed the update you applied. This issue can be closed.
