### ISSUE TITLE
Getting Error in Console and doofinder search is not working

### ISSUE THREAD

**Issue by pprignesh** [doofinder/doofinder-magento#117]
Hello;
As per below screenshot i am getting error in console and when i am typing in search box it is not showing any result. Can i how can we fix it ?
![image](https://user-images.githubusercontent.com/16082790/43440788-2e95300e-94b6-11e8-9ff2-bec15ecc2de8.png)

Thanks

**Comment by carlosescri** [comment]
Hi @pprignesh, please, contact [support](mailto:support@doofinder.com), this is not related to the module. Thanks!
