### ISSUE TITLE
convert html entities when using API

### ISSUE THREAD

**Issue by JoeZ99** [doofinder/doofinder-magento#120]
use case:
some product described like this in the product feed (generated by our plugin):

```xml
<item>
 <id><![CDATA[8596]]></id>
 <brand><![CDATA[L&#039;Outil Parfait]]></brand>
</item>
```

As can be seen the "brand" value (`L'Outil Parfait`) is html-escaped (`L&#039;Outil Parfait`)

when processing this as an file feed, the `html_entities` filter takes care of that, but:

when using the `reindex` feature of our magento plugin, our plugin uses `php-doofinder` to access doofinder's API, and uploads everything again via API. And **there's no `html_entities` filter** in that scenario.

I guess our plugin should either doesn't produce html-escaped values, or unescaping then when reading from the magento products database, or taking care of unescaping them before submitting them via API.

@carlosescri 

let know Adrien about this when it's done

https://doofinder.freshdesk.com/a/tickets/14230

**Comment by carlosescri** [comment]
Are you sure this is for Magento 1.x? we don't index by API in this module.

**Comment by JoeZ99** [comment]
Of course I'm not sure. I didn't know this was only magento 1.x, is there any repo for magento 2.x ??

**Comment by carlosescri** [comment]
https://github.com/doofinder/doofinder-magento2

**Comment by JoeZ99** [comment]
joder, si es perro me muerde
