### ISSUE TITLE
Prices of grouped products are displayed without VAT when the store is configured to display prices including VAT

### ISSUE THREAD

**Issue by carlosescri** [doofinder/doofinder-magento#2]

**Comment by JoeZ99** [comment]
a un cliente le ha pasado (https://doofinder.desk.com/agent/case/2363)

avisarles cuando esté. ellos son Sergi Hernandez <shernandez@omitsis.com>


El caso detectado es:
En el buscador de animalear.com probad a buscar "royal canin vd canine
gastro intestinal low fat (lata)" y aparecerá con el precio de 2.91 € pero
si entramos en la ficha (
http://animalear.com/royal-canin-vd-canine-gastro-intestinal-low-fat-lata.html)
el precio que debe tener (con el IVA incluido es de 3,20 €).

**Comment by carlosescri** [comment]
Devs can't reproduce the error in latest version.
